# Threshold analysis for key housing features

This notebook calculates Q1, Q3, IQR, the lower and upper outlier thresholds, and the 95th and 99th percentiles for `road_width`, `frontage`, `bedrooms`, and `bathrooms`.

In [ ]:
import pandas as pd

DATA_PATH = '../Dataset/batdongsan_real_estate_cleaned.csv'
FEATURES = {
    'road_width': 'road_width',
    'frontage': 'frontage',
    'bedroom': 'bedrooms',
    'bathroom': 'bathrooms',
    'price_trend_1y': 'price_trend_1y',
}

df = pd.read_csv(DATA_PATH)

rows = []
for label, column in FEATURES.items():
    values = pd.to_numeric(df[column], errors='coerce').dropna()

    q1 = values.quantile(0.25)
    q3 = values.quantile(0.75)
    iqr = q3 - q1
    threshold_low = q1 - 1.5 * iqr
    threshold_high = q3 + 1.5 * iqr
    p95 = values.quantile(0.95)
    p99 = values.quantile(0.99)

    rows.append({
        'feature': label,
        'source_column': column,
        'Q1': q1,
        'Q3': q3,
        'IQR': iqr,
        'thresholdLow': threshold_low,
        'thresholdHigh': threshold_high,
        'p95': p95,
        'p99': p99,
        'count': int(values.shape[0]),
    })

threshold_summary = pd.DataFrame(rows)
threshold_summary

,feature,source_column,Q1,Q3,IQR,thresholdLow,thresholdHigh,p95,p99,count
0,road_width,road_width,5.0,12.0,7.0,-5.50,22.50,30.0,45.920,2009
1,frontage,frontage,4.0,7.0,3.0,-0.50,11.50,13.0,20.000,2363
2,bedroom,bedrooms,2.0,5.0,3.0,-2.50,9.50,13.0,28.490,3452
3,bathroom,bathrooms,2.0,5.0,3.0,-2.50,9.50,12.0,28.360,3265
4,price_trend_1y,price_trend_1y,5.6,21.5,15.9,-18.25,45.35,41.7,68.954,3974

In [7]:
threshold_summary.round(3)

,feature,source_column,Q1,Q3,IQR,thresholdLow,thresholdHigh,p95,p99,count
0,road_width,road_width,5.0,12.0,7.0,-5.50,22.50,30.0,45.920,2009
1,frontage,frontage,4.0,7.0,3.0,-0.50,11.50,13.0,20.000,2363
2,bedroom,bedrooms,2.0,5.0,3.0,-2.50,9.50,13.0,28.490,3452
3,bathroom,bathrooms,2.0,5.0,3.0,-2.50,9.50,12.0,28.360,3265
4,price_trend_1y,price_trend_1y,5.6,21.5,15.9,-18.25,45.35,41.7,68.954,3974